//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVUKATLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVUKATLAR()
        {
            this.ICRALAR = new HashSet<ICRALAR>();
            this.URUNLER = new HashSet<URUNLER>();
        }
    
        public System.Guid AVUKATID { get; set; }
        public string AVUKATAD { get; set; }
        public string AVUKATSOYAD { get; set; }
        public Nullable<System.Guid> AVUKATKULLANICIADIID { get; set; }
        public string AVUKATCEPTELNO { get; set; }
        public string AVUKATISTELNO { get; set; }
        public Nullable<System.Guid> AVUKATAVANSHESAPSUBEID { get; set; }
        public string AVUKATAVANSHESAPNO { get; set; }
        public string AVUKATTIPI { get; set; }
        public Nullable<System.Guid> AVUKATMUSTERIID { get; set; }
        public Nullable<System.Guid> AVUKATSEHIRID { get; set; }
        public Nullable<System.Guid> AVUKATILCEID { get; set; }
        public string AVUKATEMAIL { get; set; }
        public string AVUKATTAMADRES { get; set; }
        public string AVUKATTCKN { get; set; }
    
        public virtual ILCELER ILCELER { get; set; }
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual SEHIRLER SEHIRLER { get; set; }
        public virtual SUBELER SUBELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICRALAR> ICRALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUNLER> URUNLER { get; set; }
    }
}
