//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICRALAR_IHTARLAR
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ICRAID { get; set; }
        public Nullable<System.Guid> IHTARID { get; set; }
    }
}
