//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ICRALAR
    {
        public System.Guid ICRAID { get; set; }

        public string ICRAUYAPDOSYANO { get; set; }

        public string ESASYILNO { get; set; }

        public Nullable<System.Guid> ICRAAVUKAT { get; set; }

        public Nullable<System.DateTime> ICRATAKIPTARIHI { get; set; }

        public string ICRATAKIPTIPI { get; set; }

        public Nullable<System.Guid> ICRAMUDURLUK { get; set; }

        public string ICRAMAHIYETKODU { get; set; }
       
        public string ICRAAVUKATTEVZINO { get; set; }

        public Nullable<System.Guid> ICRAURUN { get; set; }

        public Nullable<decimal> ICRAMIKTAR { get; set; }

        public Nullable<System.Guid> ICRAIHTARID { get; set; }
    
        public virtual AVUKATLAR AVUKATLAR { get; set; }
        public virtual IHTARLAR IHTARLAR { get; set; }
        public virtual MUDURLUKLER MUDURLUKLER { get; set; }
        public virtual URUNLER URUNLER { get; set; }
    }
}
