//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHTARLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHTARLAR()
        {
            this.ICRALAR = new HashSet<ICRALAR>();
        }
    
        public System.Guid IHTARID { get; set; }
        public Nullable<System.Guid> IHTARBORCLU { get; set; }
        public Nullable<System.Guid> IHTARNOTERADI { get; set; }
        public string IHTARYEVMIYENO { get; set; }
        public Nullable<System.DateTime> IHTARTARIHI { get; set; }
        public Nullable<int> IHTARSURE { get; set; }
        public Nullable<System.DateTime> IHTARTEBLIGTARIHI { get; set; }
        public Nullable<System.DateTime> IHTARTEBLIGGIRISTARIHI { get; set; }
        public Nullable<decimal> IHTARNAMENAKITTUTAR { get; set; }
        public Nullable<decimal> IHTARNAMEGAYRINAKITTUTAR { get; set; }
        public Nullable<int> IHTARNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICRALAR> ICRALAR { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual NOTERLIKLER NOTERLIKLER { get; set; }
    }
}
