//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcDbHukukTakipEntities : DbContext
    {
        public MvcDbHukukTakipEntities()
            : base("name=MvcDbHukukTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AVUKATLAR> AVUKATLAR { get; set; }
        public virtual DbSet<BORCLUTURLERI> BORCLUTURLERI { get; set; }
        public virtual DbSet<ICRALAR> ICRALAR { get; set; }
        public virtual DbSet<ICRALAR_IHTARLAR> ICRALAR_IHTARLAR { get; set; }
        public virtual DbSet<IHTARLAR> IHTARLAR { get; set; }
        public virtual DbSet<ILCELER> ILCELER { get; set; }
        public virtual DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual DbSet<KULLANICIROL> KULLANICIROL { get; set; }
        public virtual DbSet<MUDURLUKLER> MUDURLUKLER { get; set; }
        public virtual DbSet<MUSTERILER> MUSTERILER { get; set; }
        public virtual DbSet<NOTERLIKLER> NOTERLIKLER { get; set; }
        public virtual DbSet<SEHIRLER> SEHIRLER { get; set; }
        public virtual DbSet<SUBELER> SUBELER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
    }
}
