//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERILER()
        {
            this.AVUKATLAR = new HashSet<AVUKATLAR>();
            this.IHTARLAR = new HashSet<IHTARLAR>();
            this.URUNLER = new HashSet<URUNLER>();
        }
    
        public System.Guid MUSTERIID { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERINO { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERISOYAD { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERITCKN { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public Nullable<System.DateTime> MUSTERIDOGUMTARIHI { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIDOGUMYERI { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERICINSIYET { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIMEDENIDURUM { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIBABABAAD { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIANNEAD { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public Nullable<System.Guid> MUSTERISEHIRID { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public Nullable<System.Guid> MUSTERIILCEID { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERISEMT { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string MUSTERIBORCLUTIPI { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public Nullable<System.Guid> MUSTERIBORCLUTURUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVUKATLAR> AVUKATLAR { get; set; }
        public virtual BORCLUTURLERI BORCLUTURLERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHTARLAR> IHTARLAR { get; set; }
        public virtual ILCELER ILCELER { get; set; }
        public virtual SEHIRLER SEHIRLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUNLER> URUNLER { get; set; }
    }
}
