//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HukukTakipYeniProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.ICRALAR = new HashSet<ICRALAR>();
        }
    
        public System.Guid URUNID { get; set; }
        public Nullable<System.Guid> URUNBORCLUID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<decimal> URUNTAKIPMIKTAR { get; set; }
        public Nullable<System.DateTime> URUNTAKIPTARIHI { get; set; }
        public string URUNTAKIPBIRIMKODU { get; set; }
        public string URUNTAKIPMUDINO { get; set; }
        public Nullable<System.Guid> URUNAVUKATID { get; set; }
    
        public virtual AVUKATLAR AVUKATLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICRALAR> ICRALAR { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
    }
}
